import type { DokumenItem } from "@/app/dokumen-puu/[kategori]/DokumenClient";

export const dummyData: DokumenItem[] = [
  {
    kategori: "program-penyusunan-puu",
    jenis: "peraturan",
    nomor: "35",
    judul:
      "Program Penyusunan Peraturan Undang - Undang Nomor 35 Tahun 2025 tentang Penyelenggaraan Pelatihan dan Sertifikasi Kompetensi SDM Pertanian",
    penerbit: "-",
    instansi: "Biro Hukum",
    tahun: 2025,
    tematik: "Peraturan Undang - Undang",
    slug: "program-35-tahun-2025",
  },
  {
    kategori: "program-penyusunan-puu",
    jenis: "peraturan",
    nomor: "36",
    judul:
      "Program Penyusunan Peraturan Undang - Undang Nomor 36 Tahun 2025 tentang Fasilitasi Asuransi Pertanian",
    penerbit: "-",
    instansi: "Biro Hukum",
    tahun: 2025,
    tematik: "Peraturan Undang - Undang",
    slug: "program-36-tahun-2025",
  },
  {
    kategori: "rancangan-puu",
    jenis: "putusan",
    nomor: "RPP-01",
    judul: "Rancangan Peraturan Pemerintah tentang Ketahanan Pangan Nasional",
    penerbit: "-",
    instansi: "Biro Hukum",
    tahun: 2024,
    tematik: "Peraturan Undang - Undang",
    slug: "rpp-ketahanan-pangan",
  },
  {
    kategori: "naskah-akademik",
    jenis: "putusan",
    nomor: "RPP-01",
    judul: "Naskah Akademik Peraturan Pemerintah No 99 Tahun 2025",
    penerbit: "-",
    instansi: "Biro Hukum",
    tahun: 2024,
    tematik: "Peraturan Undang - Undang",
    slug: "naskah-akademik-permentan",
  },
  {
    kategori: "kajian-penelitian-hukum",
    jenis: "monografi",
    nomor: "KH-2024-01",
    judul:
      "Kajian Hukum Terhadap Implementasi Undang-Undang Karantina Pertanian",
    penerbit: "-",
    instansi: "Biro Hukum",
    tahun: 2024,
    tematik: "Peraturan Undang - Undang",
    slug: "kajian-hukum-karantina-pertanian",
  },
  {
    kategori: "kajian-penelitian-hukum",
    jenis: "monografi",
    nomor: "KH-2023-02",
    judul: "Kajian Evaluasi Kebijakan Perkebunan Berkelanjutan",
    penerbit: "-",
    instansi: "Biro Hukum",
    tahun: 2023,
    tematik: "Buku Hukum",
    slug: "kajian-evaluasi-perkebunan",
  },
  {
    kategori: "risalah-pembahasan",
    jenis: "artikel",
    nomor: "Pembahasan No 99 2025",
    judul: "Pembahasan Evaluasi Kebijakan Perkebunan Berkelanjutan",
    penerbit: "-",
    instansi: "Biro Hukum",
    tahun: 2023,
    tematik: "Peraturan Undang - Undang",
    slug: "kajian-evaluasi-perkebunan",
  },
];
